### ISSUE TITLE
Mongoose error

### ISSUE THREAD

**Issue by elnoidelkargol** [generalgmt/RESTfulAPITutorial#1]
When I run the server it throw's me this error: 

> /opt/lampp/htdocs/RESTfulAPITutorial/node_modules/mongoose/lib/connection.js:309
  var promise = new Promise.ES6(function(resolve, reject) {
                ^
TypeError: undefined is not a function
    at NativeConnection.Connection.open (/opt/lampp/htdocs/RESTfulAPITutorial/node_modules/mongoose/lib/connection.js:309:17)
    at Mongoose.connect (/opt/lampp/htdocs/RESTfulAPITutorial/node_modules/mongoose/lib/index.js:242:47)
    at Object.<anonymous> (/opt/lampp/htdocs/RESTfulAPITutorial/server.js:9:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
[nodemon] app crashed - waiting for file changes before starting...

Ths !

**Comment by generalgmt** [comment]
@elnoidelkargol This I believe is due to the fact that you are using a windows machine, which is difficult for me to reproduce. I'll look into it and see how best I could be off help.
